LUT-27586: Updated the form used in the task to send a custom (manual) email
lutece-secteur-public/gru-module-workflow-appointment pull request #13
Opened 2024-04-26 10:35 UTC by atos-mohamed-b

The following PR should be merged first:
- https://github.com/lutece-secteur-public/gru-module-workflow-appointment/pull/12

2024-05-24 10:30 UTC, seboo requested changes

2024-05-24 10:30 UTC, seboo commented on src/java/fr/paris/lutece/plugins/workflow/modules/appointment/provider/AppointmentNotificationMarkers.java
> +        collectionNotifyMarkers.add( createMarkerValues( AppointmentWorkflowConstants.MARK_URL_REPORT, strUrlReport.replaceAll( "&", "&amp;" ) ) );
Encoding the "&" char shoud be done in the template, like "${url?html}"
(the url value can be used in <href> tag)

2024-05-24 10:30 UTC, seboo commented on src/java/fr/paris/lutece/plugins/workflow/modules/appointment/provider/AppointmentNotificationMarkers.java
> +        infoMarker.setValue( strMarkerValue );
Use new setData( ) method to send the object in the model to the template

2024-05-24 10:30 UTC, seboo commented on src/java/fr/paris/lutece/plugins/workflow/modules/appointment/provider/AppointmentNotificationMarkers.java
> +        collectionNotifyMarkers.add( createMarkerValues( AppointmentWorkflowConstants.MARK_TIME_APPOINTMENT, _appointment.getStartingTime( ).toString( ) ) );
send the date as object

2024-05-24 10:30 UTC, seboo commented on src/java/fr/paris/lutece/plugins/workflow/modules/appointment/provider/AppointmentNotificationMarkers.java
> +        collectionNotifyMarkers.add( createMarkerValues( AppointmentWorkflowConstants.MARK_END_TIME_APPOINTMENT, _appointment.getEndingTime( ).toString( ) ) );
idem

2024-05-24 10:30 UTC, seboo commented on src/java/fr/paris/lutece/plugins/workflow/modules/appointment/provider/AppointmentNotificationMarkers.java
> +        infoMarker.setDescription( I18nService.getLocalizedString( strMarkerDescription, I18nService.getDefaultLocale( ) ) );
the locale should be sent as parameter

2024-05-27 08:55 UTC, atos-mohamed-b commented
The PR has now been rebased on the previous code:
- https://github.com/lutece-secteur-public/gru-module-workflow-appointment/pull/12

A Redmine issue to rework the module has been created:
- https://dev.lutece.paris.fr/bugtracker/issues/27872

2024-07-05 15:18 UTC, merged